website/models.py
from . import db
from flask_login import UserMixin



class Products(db.Model):
    product_id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    description = db.Column(db.Text)
    price = db.Column(db.Numeric(10,2))
    carbon_footprint = db.Column(db.Numeric(10,2))
    #user_reviews = db.relationship('user_reviews')


class User_accounts(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True)
    password = db.Column(db.String(255))
    username = db.Column(db.String(255))
    #user_reviews = db.relationship('user_reviews')



##class User_reviews(db.Model, UserMixin):
#    id = db.Column(db.Integer, primary_key=True)
 #   user_id = db.Column(db.Integer, db.ForeignKey('User_accounts.user_id'))
  #  product_id = db.Column(db.Integer, db.ForeignKey('Products.product_id'))
  #  rating = db.Column(db.Integer)
  #  comment = db.Column(db.Text)
  #  created_at = db.Column(db.DateTime(timezone=True), default=func.now())##

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'I LOVVEEE CHAIRSS'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        from .models import User_accounts
        return User_accounts.query.get(int(id))

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    with app.app_context():
        db.create_all()

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Database created!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User_accounts
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User_accounts.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('We do not recognize this email.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('username')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User_accounts.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(username) < 2:
            flash('username must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 5:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User_accounts(email=email, username=username, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, redirect, url_for, session, flash, request
from flask_login import current_user, login_required
from .models import Products, User_accounts
from .dbinit import insert_products
from . import db

views = Blueprint('views', __name__)


@views.route('/', methods=['GET'])
def home():
    try:
        # Insert initial data into database
        insert_products()
    except Exception as e:
        # Handle any errors that occur during insertion
        print("Error inserting data: ", e)

    # Retrieve all products from database
    products = Products.query.all()

    return render_template('home.html', products=products, user=current_user)


@views.route('/add_to_cart/<int:product_id>', methods=['POST'])
def add_to_cart(product_id):
    # get the current cart list from session or create an empty one
    cart = session.get('cart', [])

    # add the product_id to the cart list
    cart.append(product_id)

    # update the cart list in the session
    session['cart'] = cart

    # redirect to the cart page
    return redirect(url_for('views.cart'))


@views.route('/cart', methods=['GET', 'POST'])
@login_required
def cart():
    # Retrieve the cart list from the Flask session
    cart = session.get('cart', [])

    # Create a dictionary to hold the product information
    products = {}

    # Query the database for the product information
    for product_id in set(cart):
        product = Products.query.filter_by(product_id=product_id).first()
        if product:
            products[product_id] = {
                'name': product.name,
                'price': product.price,
                'quantity': cart.count(product_id)
            }

    # Calculate the total price of all items in the cart
    total_price = sum(products[product_id]['price'] * products[product_id]['quantity'] for product_id in products)

    # Update the cart with the new quantity values
    if request.method == 'POST':
        for product_id, product in products.items():
            quantity = request.form.get('quantity{}'.format(product_id))
            if quantity:
                update_cart(product_id, int(quantity))

    return render_template('cart.html', products=products, total_price=total_price, user = current_user)


@views.route('/update_cart/<int:product_id>', methods=['POST'])
def update_cart(product_id):
    # Retrieve the cart list from the Flask session
    cart = session.get('cart', [])

    # Update the quantity of the product in the cart
    for i, item in enumerate(cart):
        if item == product_id:
            cart[i] = product_id
            break

    # Remove any products from the cart with a quantity of 0
    cart = [item for item in cart if cart.count(item) > 0]

    # Update the cart list in the session
    session['cart'] = cart

    return redirect(url_for('views.cart'))



@views.route('/remove_from_cart/<int:product_id>', methods=['POST'])
def remove_from_cart(product_id):
    # Retrieve the cart list from the Flask session
    cart = session.get('cart', [])

    # Remove the product_id from the cart list
    cart.remove(product_id)

    # update the cart list in the session
    session['cart'] = cart

    # redirect to the cart page
    return redirect(url_for('views.cart'))

website/templates/base.html
<!DOCTYPE html>
<html>
  <body style="background-color:rgb(250, 246, 20);"></body>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="../static/css/stylesheet.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script defer src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.3/umd/popper.min.js" integrity="sha512-DIttuZqQI7E7A/hfip5wuA5XLd03+Y3XQ5tmjx76nlCbOJZYfvncCf3MMb0E45K16zACJntBDJzUePw+0eZ/1g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.1/js/bootstrap.min.js" integrity="sha512-6nGbr6T25PYbD+J78Sykjz8T5c7Lv1PkRYD28Rn73qj8i0XysVr1qf5CHY43ahveBrr5El8dMQb3OhkNCpYl4A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.1/css/bootstrap.min.css" integrity="sha512-XK/7vMqZZsV1StlSK2X0dJ/YVzTFQ+3b8E9LwXbTc8sGcD6kWzrmR3zwL9ZJkgrPYE6H+ZI7Nf2OZI8DmlWpjg==" crossorigin="anonymous" referrerpolicy="no-referrer">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.1/css/bootstrap-theme.min.css" integrity="sha512-eiJj44FPRJv0W3WxakJzc3pDc0gL5vPeXf7pJokS/9s2sOjH8nbJwTnQf7v5JGr9v7zI99/1Lj8mCQx4J1DIIg==" crossorigin="anonymous" referrerpolicy="no-referrer">

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #F4D504;">
      
      <img src="..\static\Assets\Chairs-1.png" class="img-fluid" alt="Responsive image" style="max-height: 250px;">
      
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav ms-5" style="font-size: 70px; ">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link text-black" id="home" href="/">Home.</a>
          <a class="nav-item nav-link text-black" id="logout" href="/logout">Logout.</a>
          <a class="nav-item nav-link text-black" id = "cart" href="/cart">Cart.</a>
          
          
          {% else %}
          <a class="nav-item nav-link text-black" id="home" href="/">Home.</a>
          <a class="nav-item nav-link text-black" id="login" href="/login">Login.</a>
          <a class="nav-item nav-link text-black" id="signUp" href="/sign-up">Sign-Up.</a>
          

          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} 
    {% if messages %} 
    {% for category, message in messages %} 
    {% if category == 'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
  
    {% block cart %}
    {% if session.cart %}
    <span class="badge badge-pill badge-primary">{{ session.cart|length }}</span>
    {% endif %}
    {% endblock %}

    
  </body>
</html>

website/templates/cart.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-5">
    <h1>Your Cart</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Quantity</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for product_id, product in products.items() %}
          <tr>
            <th scope="row">{{ loop.index }}</th>
            <td>{{ product['name'] }}</td>
            <td>${{ product['price'] }}</td>
            <td>
              <form action="{{ url_for('views.cart') }}" method="POST">
                <div class="input-group">
                  <input type="number" name="quantity" value="{{ product['quantity'] }}" min="1" class="form-control" aria-label="Quantity" aria-describedby="basic-addon2">
                  <div class="input-group-append">
                    <button class="btn btn-primary" type="submit">Update</button>
                  </div>
                </div>
              </form>
            </td>
            <td>
              <form action="{{ url_for('views.remove_from_cart', product_id=product_id) }}" method="POST">
                <button class="btn btn-danger" type="submit">Remove</button>
              </form>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <p class="lead">Total Price: ${{ total_price }}</p>
    <a href="{{ url_for('views.home') }}" class="btn btn-primary">Continue Shopping</a>
  </div>
{% endblock %}

website/templates/checkout.html
{% extends "base.html" %}
{% block title %}Checkout{% endblock %}
{% block page %}
<div class="container py-4 py-xl-5" style="font-family: 'RamaGothicEW01';">
<div class="row mb-5">
<div class="col-md-8 col-xl-6 text-center mx-auto" style="margin-bottom: 40px">
<h2 style="font-family: RamaGothicEW01;font-weight: bold;letter-spacing: 2px;font-size: 48px;color: #ff2e00;margin-bottom: 0px;">CHECKOUT</h2>
</div>
<form method="POST" id="checkoutForm" action="">
<div style="width:90%;position: relative;margin: auto">
<div style='height: 80px;margin:10px 30px;'>
<div class="d-flex" style="width: 80%;margin:auto">
<div style="margin-left:100px;height: 60px;width: auto;padding: 5px">
<div style="margin-top: 14px;font-size: 24px">
CREDIT CARD NUMBER
</div>
</div>
<div style="margin-left: auto;margin-right:100px;margin-top:14px;height:60px">
<input id="ccn" class='input-ccn form-control' style="width:200px;text-align: center;margin-right: 60px;margin-top:10px" type="tel" placeholder="XXXX XXXX XXXX XXXX"/>
</div>
<div class="btn-clear hidden-right">clear</div>
</div>
</div>
<div style='height: 80px;margin:20px 30px;'>
<div class="d-flex" style="width: 80%;margin:auto">
<div style="height: 60px;margin-left:150px;width: auto;padding: 5px">
<div style="margin-top: 14px;font-size: 24px">
EXPIRY DATE
</div>
</div>
<div style="margin-left: auto;margin-right:150px;margin-top:14px;height:60px">
<input id="exp" class='input-exp form-control' style="width:100px;text-align: center;margin-right: 60px;margin-top:10px" type="text" placeholder="MM/YY"/>
</div>
</div>
</div>
<div style='height: 80px;margin:20px 30px;'>
<div class="d-flex" style="width: 80%;margin:auto">
<div style="height: 60px;margin-left:160px;width: auto;padding: 5px">
<div style="margin-top: 14px;font-size: 24px">
CVC / CCV
</div>
</div>
<div style="margin-left: auto;margin-right:150px;margin-top:14px;height:60px">
<input id="cvc" class='input-cvc form-control' style="width:100px;text-align: center;margin-right: 60px;margin-top:10px" type="number" placeholder="XXX"/>
</div>
</div>
</div>
<div style="margin:10px;text-align: center">
{% if user.is_authenticated %}
<button class="btn btn-danger checkout-button" type="submit">SUBMIT</button>
<input class="hidden" type="text" name="user" id="user" value="user"/>
{% else %}
<button class="btn btn-danger checkout-button" type="submit">SUBMIT</button>
<input class="hidden" type="text" name="user" id="user" value="anon"/>
{% endif %}
</div>
</div>
</form>
</div>
</div>
</div>
{% endblock %}
{% block scripts %}
<script src="../static/js/checkout.js"></script>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %} 

{% block content%}
  <div class="container">
    <div class="row">
      <div class="col-md-1">
        <img src="{{ url_for('static', filename='Assets/cheapdogs.gif') }}" class="rounded left-align">
      </div>
      <div class="col-md-11">
        <div class="row row-cols-1 row-cols-md-3 g-4">
          {% for product in products %}
          <div class="col mb-4">
            <div class="card card-fixed">
              <div class="card-body">
                <img class="card-img-top" src="{{ url_for('static', filename='Assets/' + product['name'] + '.png') }}">
                <h5 class="card-title">{{ product['name'] }}</h5>
                <p class="card-text"><strong>Price: £{{ product['price'] }}</strong></p>
                <button class="btn btn-outline-dark toggle-description-btn" data-toggle="collapse" data-target="#product-description-{{ loop.index }}">Show Description</button>
                <div id="product-description-{{ loop.index }}" class="collapse product-description">
                  <p>{{ product['description'] }}</p>
                  <p>This product has a carbon footprint of {{ product['carbon_footprint'] }} KG of CO2.</p>
                </div>
                {% if current_user.is_authenticated %}
                <form action="{{ url_for('views.add_to_cart', product_id=product['product_id']) }}" method="POST">
                    <input type="hidden" name="product_id" value="{{ product['product_id'] }}">
                    <button class="btn btn-outline-dark add-to-cart" type="submit">Add to Cart</button>
                </form>
                {% else %}
                <button class="btn btn-outline-dark" disabled>Add to Cart</button>
                <span class="badge bg-warning text-danger">Please login or sign-up to add items to cart</span>
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
        </div>
      </div>
    </div>
  </div>


  <script src="{{ url_for('static', filename='js/descriptiontoggle.js') }}"></script>

{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content%}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <div class="d-flex justify-content-center">
    <button type="submit" class="btn btn-outline-dark btn-lg btn-block">Submit</button>
  </div>
   
</form>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="username">Username</label>
    <input
      type="text"
      class="form-control"
      id="username"
      name="username"
      placeholder="Enter username"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  
<div class="d-flex justify-content-center">
  <button type="submit" class="btn btn-outline-dark btn-lg btn-block">Submit</button>
</div>
 
</form>
{% endblock %}